version: "3.1"
services:
    ui:
        container_name: gisma_ui
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "8081:3000"
        environment:
            - REACT_APP_API_URL=${REACT_APP_API_URL}
            - REACT_APP_API_PORT=${REACT_APP_API_PORT}
    app:
        container_name: gisma_api
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
    db:
        image: mysql
        container_name: gisma_db
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: gisma_phpmyadmin
        links: 
            - db:db
        ports:
            - 8010:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: t3FCJu5k2VPaB3
            MYSQL_ROOT_PASSWORD: t3FCJu5k2VPaB3
volumes:
    persistent:
